### ISSUE TITLE
Avantes spectrometers in parallel?

### ISSUE THREAD

**Issue by Saldenisov** [MSLNZ/msl-equipment#10]
I have no idea how to solve the problem when two spectrometers are supposed to work in parallel. Depending on which one starts the first, the only one will work, another will be locked (no polling is possible for it).

I even made a copy of a DLL, thinking that ctypes is locking DLL functions somehow. 

What could be the reason?

**Comment by jborbely** [comment]
We only have access to one Avantes spectrometer, so we cannot test ``msl-equipment`` (nor any of the example programs that are installed when the Avantes SDK is installed) with more than one spectrometer.

Does your program work when you acquire data from the spectrometers sequentially? If you are looking for parallelization, perhaps the Avantes DLL does not support this feature. Could be helpful if you ask Avantes if the DLL supports parallelization.

When calling the ``AVS_Activate`` function in the DLL, a unique handle is supposed to be returned. Passing this handle to subsequent DLL functions (which ``msl-equipment`` does) is supposed to process the DLL function for a particular handle (i.e., spectrometer). Verify that the handle for each spectrometer is unique, for example, something like

```python
from msl.equipment import EquipmentRecord, ConnectionRecord

record1 = EquipmentRecord(
    manufacturer='Avantes',
    serial='1807344U1',  # update for your device
    connection=ConnectionRecord(address='SDK::avaspecx64.dll')
)

record2 = EquipmentRecord(
    manufacturer='Avantes',
    serial='1807344U2',  # update for your device
    connection=ConnectionRecord(address='SDK::avaspecx64.dll')
)

spectrometer1 = record1.connect()
spectrometer2 = record2.connect()
print(spectrometer1._handle)
print(spectrometer2._handle)
```
Avantes provides example programs written in various programming languages when the SDK is installed. In particular, the code in ``...\examples\Delphi XE3\multichannel`` is supposed to allow for multiple spectrometers to be used. I suggest that you verify that the Delphi example works. There is also a Python example in ``..\examples\PyQt5`` that you may want to test (and modify) to see if multiple spectrometers can be used in parallel.

Also, it would be appreciated if you provide feedback for the other questions you have asked (#9) where we are waiting for a reply to our suggestions and our questions.

**Comment by Saldenisov** [comment]
INPUT:
`from msl.equipment import EquipmentRecord, ConnectionRecord, Backend

record1 = EquipmentRecord(
    manufacturer='Avantes',
    model='AvaSpec-2048L',  # update for your device
    serial='1810225U1',  # update for your device
    connection=ConnectionRecord(
        address='SDK::C:/dev/pyconlyse/DeviceServers/AVANTES_CCD/avaspecx64.dll'
    )
)

record2 = EquipmentRecord(
    manufacturer='Avantes',
    model='AvaSpec-2048L',  # update for your device
    serial='1810226U1',  # update for your device
    connection=ConnectionRecord(
        address='SDK::C:/dev/pyconlyse/DeviceServers/AVANTES_CCD/avaspecx64.dll'
    )
)

spectrometer1 = record1.connect()
print(spectrometer1._handle)
spectrometer2 = record2.connect()
print(spectrometer2._handle)`

OUTPUT
`C:\Users\elyse\.conda\envs\pyconlyse39\python.exe C:/dev/pyconlyse/DeviceServers/AVANTES_CCD/avaspec_test2.py
1
2
Avantes<Avantes|AvaSpec-2048L|1810226U1 at SDK::C:/dev/pyconlyse/DeviceServers/AVANTES_CCD/avaspecx64.dll> The <_FuncPtr object at 0x000001FC035C1BA0> function returned False
Exception ignored in: <function Connection.__del__ at 0x000001FC023BD0D0>
Traceback (most recent call last):
  File "C:\Users\elyse\.conda\envs\pyconlyse39\lib\site-packages\msl\equipment\connection.py", line 72, in __del__
  File "C:\Users\elyse\.conda\envs\pyconlyse39\lib\site-packages\msl\equipment\resources\avantes\avaspec.py", line 1052, in disconnect
  File "C:\Users\elyse\.conda\envs\pyconlyse39\lib\site-packages\msl\equipment\resources\avantes\avaspec.py", line 774, in deactivate
  File "C:\Users\elyse\.conda\envs\pyconlyse39\lib\site-packages\msl\equipment\resources\avantes\avaspec.py", line 751, in _check_bool
  File "C:\Users\elyse\.conda\envs\pyconlyse39\lib\site-packages\msl\equipment\connection.py", line 91, in raise_exception
msl.equipment.exceptions.AvantesError: Avantes<Avantes|AvaSpec-2048L|1810226U1 at SDK::C:/dev/pyconlyse/DeviceServers/AVANTES_CCD/avaspecx64.dll>
The <_FuncPtr object at 0x000001FC035C1BA0> function returned False`

**Comment by jborbely** [comment]
The handles are unique. The two print statements show `1` and `2`. 

The error in your OUTPUT is the same as #5. I have just pushed an attempt to fix that error when multiple spectrometers are used and the connections are closed. Update your installed version of `msl-equipment` with the _main_ branch. Hopefully, if you re-run your `avaspec_test2.py` script you will see the values of the handles printed and no error will occur.

Please let us know if the _main_ branch fixed the error shown in your OUTPUT.

**Comment by Saldenisov** [comment]
It worked:) But I was forced to copy the code from avaspec.py directly to mine `msl update equipment` did not work.

**Comment by Saldenisov** [comment]
The issue with reading from two spectrometers in parallel persists. Lets see what AVANTES will respond.

**Comment by jborbely** [comment]
Running
```console
msl update equipment
```
first checks PyPI for the latest release and if no releases are found checks GitHub for the latest release. There is only a 0.1.0 release available on GitHub. Since your installed version is either 0.1.0 or 0.2.0.dev0 there is nothing to update.

If you want to update your installed version from a GitHub branch (not from a release) you should run
```console
msl update equipment --branch main
```
Please keep us updated with the information that Avantes provides you with.

**Comment by jborbely** [comment]
Hopefully Avantes has provided you with the necessary support.

Closing this issue since there is nothing that can be fixed by `msl-equipment`. The issue must be fixed within the SDK provided by Avantes.

**Comment by Saldenisov** [comment]
@jborbely, thanks for trying. I will try to push AVANTES. I was busy with other work, the project will be revisited again. Wish me luck. If it works, I will let you know%)
