### ISSUE TITLE
Publish package on PyPI?

### ISSUE THREAD

**Issue by ivalaginja** [MSLNZ/msl-equipment#13]
Hey guys,

Hello from Paris! You did some very neat work with this library! I was curious whether there were any plans to release it on PyPI like some of the other MSLNZ packages?

Cheers!
Iva

**Comment by jborbely** [comment]
Thank you for reaching out and for the kind comments.

Yes, there are plans to eventually release it on PyPI. There are two sides of `msl-equipment` &dash; 1) interfacing with equipment, 2) managing information about equipment. Achieving (1) is fairly straight forward; however, as an [ISO/IEC 17025](https://www.iso.org/standard/66912.html) accredited National Metrology Institute (New Zealand's equivalent to France's [LNE](https://www.lne.fr/en)) we are still discussing how to best achieve (2) for our quality infrastructure. For a grad student/postdoc using this library, (2) is not that important and it is primarily (1) that is useful. It is internal discussions about (2) that is delaying a PyPI release.

We have recently restarted these discussions and hopefully that means there could soon (months?) be a release on PyPI. The PyPI release still won't be at version 1.0, which means that the API will not be stable yet.

I'll close this issue, as I assume you were just curious about what the response would be, but please feel free to reply to it (or create a new issue) should you have additional comments or questions.

**Comment by ivalaginja** [comment]
Thanks a lot for the detailed answer! Indeed, I was just curious about getting some info. In this case, I'll keep my eye on your repo in the next couple of months/over the next year. Thanks a lot!
