### ISSUE TITLE
Thorlabs Kinesis KST101 FT_DeviceNotFound exception

### ISSUE THREAD

**Issue by jrr1984** [MSLNZ/msl-equipment#2]
KCubeStepperMotor<Thorlabs|KST101|26001683 at SDK::Thorlabs.MotionControl.KCube.StepperMotor.dll> FT_DeviceNotFound: The device could not be found. This can be generated if the function MotionControl.build_device_list() has not been called
Traceback (most recent call last):
  File "test1.py", line 39, in <module>
    motor = record.connect()
  File "C:\Users\USUARIO\Anaconda3\lib\site-packages\msl\equipment\record_types.py", line 274, in connect
    return factory.connect(self, demo)
  File "C:\Users\USUARIO\Anaconda3\lib\site-packages\msl\equipment\factory.py", line 103, in connect
    return _connect(record)
  File "C:\Users\USUARIO\Anaconda3\lib\site-packages\msl\equipment\factory.py", line 93, in _connect
    return cls(_record)
  File "C:\Users\USUARIO\Anaconda3\lib\site-packages\msl\equipment\resources\thorlabs\kinesis\kcube_stepper_motor.py", line 63, in __init__
    super(KCubeStepperMotor, self).__init__(record, KCube_StepperMotor_FCNS)
  File "C:\Users\USUARIO\Anaconda3\lib\site-packages\msl\equipment\resources\thorlabs\kinesis\motion_control.py", line 119, in __init__
    self.open()
  File "C:\Users\USUARIO\Anaconda3\lib\site-packages\msl\equipment\resources\thorlabs\kinesis\kcube_stepper_motor.py", line 1200, in open
    self.sdk.SCC_Open(self._serial)
  File "C:\Users\USUARIO\Anaconda3\lib\site-packages\msl\equipment\resources\thorlabs\kinesis\motion_control.py", line 130, in errcheck_api
    self.raise_exception('{}: {}'.format(err_name, err_msg))
  File "C:\Users\USUARIO\Anaconda3\lib\site-packages\msl\equipment\connection.py", line 88, in raise_exception
    raise self._exception_handler('{!r}\n{}'.format(self, msg))
msl.equipment.exceptions.ThorlabsError: KCubeStepperMotor<Thorlabs|KST101|26001683 at SDK::Thorlabs.MotionControl.KCube.StepperMotor.dll>
FT_DeviceNotFound: The device could not be found. This can be generated if the function MotionControl.build_device_list() has not been called

**Comment by jborbely** [comment]
Could you please let me know the following:
1. Copy and paste the code to `test1.py` in this issue so that I can see what you're doing.
2. What version of Kinesis are you using?
3. Can you communicate with your KST101 using the Kinesis GUI?
4. Have you tried what the error message suggests to try?

> FT_DeviceNotFound: The device could not be found. This can be generated if the function MotionControl.build_device_list() has not been called

See [here](https://github.com/MSLNZ/msl-equipment/blob/master/msl/examples/equipment/resources/thorlabs/kinesis_device_info.py) for an example on how to call `MotionControl.build_device_list()`

**Comment by jrr1984** [comment]
working code below:

if __name__ == '__main__':
    import os
    from pprint import pprint

    from msl.equipment import EquipmentRecord, ConnectionRecord, Backend

    from msl.equipment.resources.thorlabs import MotionControl
    # ensure that the Kinesis folder is available on PATH
    os.environ['PATH'] += os.pathsep + 'C:/Program Files/Thorlabs/Kinesis'

    print('Building the device list...')
    MotionControl.build_device_list()
    # rather than reading the EquipmentRecord from a database we can create it manually
    record = EquipmentRecord(
        manufacturer='Thorlabs',
        model='KST101',
        serial='26001683',  # update the serial number for your KST101
        connection=ConnectionRecord(
            backend=Backend.MSL,
            address='SDK::Thorlabs.MotionControl.KCube.StepperMotor.dll',
        ),
    )

    def wait(value):
        motor.clear_message_queue()
        message_type, message_id, _ = motor.wait_for_message()
        while message_type != 2 or message_id != value:
            position = motor.get_position()
            real = motor.get_real_value_from_device_unit(position, 'DISTANCE')
            print('  at position {} [device units] {} [real-world units]'.format(position, real))
            message_type, message_id, _ = motor.wait_for_message()

    # connect to the KCube Stepper Motor
    motor = record.connect()
    print('Connected to {}'.format(motor))

    # load the configuration settings (so that we can use the get_real_value_from_device_unit() method)
    motor.load_settings()

    # start polling at 200 ms
    #motor.start_polling(200)

    # home the device
    print('Homing...')
    motor.home()
    wait(0)
    print('Homing done. At position {} [device units]'.format(motor.get_position()))

    #motor.stop_polling()
    motor.disconnect()

**Comment by jborbely** [comment]
Could you also please answer questions 2, 3 and 4?

**Comment by jrr1984** [comment]
yes my friend, i was about to!

2) What version of Kinesis are you using?
Version 1.14.15 (Build 15220)

3) Can you communicate with your KST101 using the Kinesis GUI?
Yes indeed.

4) Have you tried what the error message suggests to try?
yes, and therefore, it worked, thanks!

**Comment by jborbely** [comment]
I'm happy to hear that your issue was resolved.
